name: Build and run
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    env:
      CONTAINER_NAME: hekadump_crawl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      id: build
      run: docker build -t hekadump . && docker run --name $CONTAINER_NAME hekadump
    - name: Copy output csv from image to host
      run: docker cp $CONTAINER_NAME:${{ steps.build.outputs.output_path }} .
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.build.outputs.output_file }}
        path: ./${{ steps.build.outputs.output_file }}
