name: Build and generate dump

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 10 * * *'

jobs:
  build:
    env:
      CONTAINER_NAME: hekadump_crawl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --pull -t hekadump .
    - name: Run the program
      id: run
      run: docker run --name $CONTAINER_NAME hekadump
    - name: Copy output csv from container to host
      run: docker cp $CONTAINER_NAME:${{ steps.run.outputs.output_path }} .
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.run.outputs.output_file }}
        path: ./${{ steps.run.outputs.output_file }}
