name: Build and generate dump

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 10 * * *'

jobs:
  build:
    env:
      CONTAINER_NAME: hekadump_crawl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.13.x
    - name: Install dependencies
      run: opam install .
    - name: Build the program
      run: opam exec -- dune build
    - name: Run the program
      id: run
      run: ./release.sh
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.run.outputs.output_file }}
        path: ./${{ steps.run.outputs.output_file }}
